
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinalKermesse.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VwKermesse
{

    public int idKermesse { get; set; }

    public string Parroquia { get; set; }

    public string Kermesse { get; set; }

    public System.DateTime FechaInicio { get; set; }

    public System.DateTime FechaFinal { get; set; }

    public string Descripcion { get; set; }

}

}
