
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFinalKermesse.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VwRolOpcion
{

    public int id { get; set; }

    public string RolDescripcion { get; set; }

    public string Descripcion { get; set; }

}

}
